version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb+srv://user:password@cluster0.mongodb.net/restaurant_booking?retryWrites=true&w=majority"
    depends_on:
      - db

  db:
    image: mongo
    restart: always`
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: restaurant_booking
